name: FireJumpersPRO
favicon: null
layout_spectrum: 0.5858
typography_spectrum: 0.80908
title: FireJumpersPRO - Tactical Decision Making
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d3b09'
    - '#00cfdb'
    - '#21670d'
    - '#009700'
    - '#735106'
  brandStrength: 0.625
  lightness: 0.07801067852415144
  saturation: 0.625
  rhythmicContrast: 0.8547399502713233
purpose: []
