name: FireJumpersPRO
favicon: null
layout_spectrum: 0.24345
typography_spectrum: 0.80908
title: FireJumpersPRO - Tactical Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d3b09'
    - '#00cfdb'
    - '#21670d'
    - '#009700'
    - '#735106'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
